FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN apt-get update && apt-get install -y openssh-server
RUN sed -i -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
RUN echo "root:Abcd1234" | chpasswd

WORKDIR /src
COPY . /src
ENV ASPNETCORE_URLS=http://0.0.0.0:80
ENTRYPOINT ["/bin/sh", "-c" , "/etc/init.d/ssh start && dotnet watch run --project loops"]
