apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  labels:
    service: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sql
  template:
    metadata:
      labels:
        service: sql
    spec:
      containers:
      - name: sql
        image: mcr.microsoft.com/mssql/server:latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: SA_PASSWORD
          value: "Password1!"
---
apiVersion: v1
kind: Service
metadata:
  name: sql
  labels:
    service: sql
spec:
  selector:
    service: sql
  ports:
  - name: "1433"
    port: 1433
    targetPort: 1433
---
# ONLY FOR LOCAL DEVELOPMENT!
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  labels:
    service: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dev
  template:
    metadata:
      labels:
        service: dev
    spec:
      containers:
      - name: dev
        image: mcr.microsoft.com/dotnet/sdk:latest
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /code
          name: code-volume
      volumes:
      - name: code-volume
        hostPath:
          path: /Users/maxhorstmann/code/OneMinuteMax/Loops
          type: Directory
             

