apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  labels:
    service: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dev
  template:
    metadata:
      labels:
        service: dev
    spec:
      containers:
      - name: dev
        image: mcr.microsoft.com/dotnet/sdk:5.0
        command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0"]
        workingDir: /code/bar
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /code
          name: code-volume
      volumes:
      - name: code-volume
        hostPath:
          path: /Users/maxhorstmann/code/OneMinuteMax/Loops
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: dev
  labels:
    service: dev
spec:
  selector:
    service: dev
  type: NodePort    
  ports:
  - name: "http"
    port: 80
    nodePort: 30000
    targetPort: 80


