apiVersion: apps/v1
kind: Deployment
metadata:
  name: loops
  labels:
    service: loops
spec:
  replicas: 1
  selector:
    matchLabels:
      service: loops
  template:
    metadata:
      labels:
        service: loops
    spec:
      containers:
      - name: loops
        image: loops-dev
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loops
  labels:
    service: loops
spec:
  selector:
    service: prod
  type: LoadBalancer    
  ports:
  - name: "http"
    port: 80
    targetPort: 80


