apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod
  labels:
    service: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prod
  template:
    metadata:
      labels:
        service: prod
    spec:
      containers:
      - name: prod
        image: maxhorstmann/loops:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod
  labels:
    service: prod
spec:
  selector:
    service: prod
  type: LoadBalancer    
  ports:
  - name: "http"
    port: 80
    targetPort: 80


