apiVersion: v1
kind: Service
metadata:
  name: sql  #  TODO make PR specific{{ include "helm.fullname" . }}-sql
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1433
      protocol: TCP
      name: sql
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}-sql
