apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-sql
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}-sql
