version: "3"
services:
        sql:
                image: "microsoft/mssql-server-linux"
                ports:
                        - "1433:1433"
                environment:
                        - ACCEPT_EULA=Y
                        - MSSQL_PID=Express
                        - SA_PASSWORD=Password!
        redis:
                image: "redis"
                ports:
                        - "6379:6379"
        web:
                ports:
                        - "80:80"
