version: "3"
services:
        web:
                image: "microsoft/dotnet:sdk"
                volumes:
                        - ./web:/opt/code
                stdin_open: true
                tty: true
                working_dir: /opt/code

