name: PRBuild
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        path: AspNetCoreApp5Minutes/web
        username: maxhorstmann
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: maxhorstmann/oneminutemax/oneminutemax
        tags: pr-${{ github.event.pull_request.number }}

    # - name: Setup kubectl
    #   uses: azure/setup-kubectl@v1
    #   id: install
    # - name: Setup helm
    #   uses: azure/setup-helm@v1
    # - name: Set AKS context
    #   uses: azure/aks-set-context@v1
    #   with:
    #     creds: '${{ secrets.AKS_CREDENTIALS }}'
    #     resource-group: 'pr-builds'
    #     cluster-name: 'rehglz-aks'

    #   run: helm install --wait --set image.tag=pr-${{ github.event.pull_request.number }} aksdeploytest-pr-${{ github.event.pull_request.number }} ./helm

    # - name: Fetch IP
    #   run: echo ::set-env name=PR_ENVIRONMENT_IP::$(kubectl get svc aksdeploytest-pr-${{ github.event.pull_request.number }} --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")

    # - name: Create comment
    #   uses: peter-evans/create-or-update-comment@v1  # 3rd party - TODO build our own
    #   with:
    #     issue-number: ${{ github.event.pull_request.number }}
    #     body: "Your PR Environment is here: http://${{ env.PR_ENVIRONMENT_IP }}"
